### ISSUE TITLE
Cannot run tests on Travis

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-parcel-preprocessor#1]
Parcel bundler throws an error
```
$ npm run cy:run
> cypress-parcel-preprocessor@0.0.0-development cy:run /home/travis/build/bahmutov/cypress-parcel-preprocessor
> cypress run
It looks like this is your first time using Cypress: 1.4.2
[03:29:14]  Verifying Cypress can run /home/travis/build/bahmutov/cypress-parcel-preprocessor/node_modules/cypress/dist/Cypress [started]
[03:29:22]  Verifying Cypress can run /home/travis/build/bahmutov/cypress-parcel-preprocessor/node_modules/cypress/dist/Cypress [completed]
Opening Cypress...
The plugins file is missing or invalid.
Your pluginsFile is set to '/home/travis/build/bahmutov/cypress-parcel-preprocessor/cypress/plugins/index.js', but either the file is missing, it contains a syntax error, or threw an error when required. The pluginsFile must be a .js or .coffee file.
Please fix this, or set 'pluginsFile' to 'false' if a plugins file is not necessary for your project.
The following error was thrown:
Error: Cannot find module './SourceMapPackager'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/bahmutov/cypress-parcel-preprocessor/node_modules/parcel-bundler/lib/packagers/index.js:6:27)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/bahmutov/cypress-parcel-preprocessor/node_modules/parcel-bundler/lib/Bundler.js:27:26)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

**Comment by bahmutov** [comment]
Hmm, this error is due to Node 6 in Cypress 1.x - how is it working locally?!! Need to switch to Cypress 2.x with Node 8

https://github.com/parcel-bundler/parcel/issues/642

**Comment by bahmutov** [comment]
After upgrading have new crash
```
var getLength = Buffer.byteLength.bind(Buffer);
                      ^

TypeError: Cannot read property 'byteLength' of undefined
    at Object.<anonymous> (/Users/gleb/git/cypress-parcel-preprocessor/node_modules/truncate-utf8-bytes/index.js:4:23)
```
Maybe Node 8.2.1 bundled with Electron has a bug? Do not have this problem with Node 8.9.4. No, parcel works in Node 8.2.1 - must be some weird Electron + Buffer issue

Hmm, this is Electron deleting global Buffer https://github.com/electron/electron/pull/7114

**Comment by bahmutov** [comment]
Ok, the module that has this problem is `sanitize-filename` and it was just removed from Parcel bundler https://github.com/parcel-bundler/parcel/commit/1ceb7aa791cc4a4a2291c1f78c799182f89fc111 so I just need to wait until 1.6.3 is released

**Comment by bahmutov** [comment]
Tried using the Parcel bundler directly from commit and it is working, so whenever it is released, it should be used.
