### ISSUE TITLE
Error: Could not locate bindings file

### ISSUE THREAD

**Issue by dbnapp** [bahmutov/cypress-parcel-preprocessor#39]
Received this error in cypress 

    "cypress-parcel-preprocessor": "^1.0.0",

```
Error: Could not locate the bindings file. Tried:
 → C:\source\MyProject\node_modules\deasync\build\deasync.node
 → C:\source\MyProject\node_modules\deasync\build\Debug\deasync.node
 → C:\source\MyProject\node_modules\deasync\build\Release\deasync.node
 → C:\source\MyProject\node_modules\deasync\out\Debug\deasync.node
 → C:\source\MyProject\node_modules\deasync\Debug\deasync.node
 → C:\source\MyProject\node_modules\deasync\out\Release\deasync.node
 → C:\source\MyProject\node_modules\deasync\Release\deasync.node
 → C:\source\MyProject\node_modules\deasync\build\default\deasync.node
 → C:\source\MyProject\node_modules\deasync\compiled\8.2.1\win32\x64\deasync.node
    at bindings (C:\source\MyProject\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\source\MyProject\node_modules\deasync\index.js:30:31)
    at Object.<anonymous> (C:\source\MyProject\node_modules\deasync\index.js:74:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\source\MyProject\node_modules\parcel-bundler\src\utils\syncPromise.js:1:172)
    at Object.<anonymous> (C:\source\MyProject\node_modules\parcel-bundler\src\utils\syncPromise.js:33:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

**Comment by folmert** [comment]
Same here. Doesn't seem to work on Windows.

**Comment by flotwig** [comment]
Related: https://stackoverflow.com/questions/55422822/error-could-not-locate-the-bindings-file-when-running-cypress-with-parcel

**Comment by attack-monkey** [comment]
Same here - windows too

**Comment by jhderojasUVa** [comment]
Same with version ^1.0.0 on unix environment.

The error is on the index.js inside node_modules/cypress-parcel-preprocessor/src/index.js

On the:

const ParcelBundler = require('parcel-bundler')

That doesn't "import" it.
